export default {
    PLAYING: 'PLAYING',
    STREAMING: 'STREAMING',
    LISTENING: 'LISTENING',
    WATCHING: 'WATCHING',
    CUSTOM_STATUS: 'CUSTOM_STATUS', // NOT AVAILABLE FOR BOTS
    COMPETING: 'COMPETING'
}